### ISSUE TITLE
Resque fails unless the `before_child_exit` hook is defined

### ISSUE THREAD

**Issue by greggroth** [stulentsev/resque-multi-job-forks#19]
Tested with Resque 2.0, the workers will not start unless a `before_child_exit` hook has been defined.

```
gems/resque-2.0.0/lib/resque/worker.rb:647:in `run_hook': undefined method `empty?' for nil:NilClass (NoMethodError)
    from gems/resque-multi-job-forks-0.5.0/lib/resque-multi-job-forks.rb:124:in `release_fork'
    from gems/resque-multi-job-forks-0.5.0/lib/resque-multi-job-forks.rb:105:in `release_and_exit!'
    from gems/resque-multi-job-forks-0.5.0/lib/resque-multi-job-forks.rb:35:in `work_with_multi_job_forks'
    from gems/resque-2.0.0/lib/resque/tasks.rb:20:in `block (2 levels) in <top (required)>'
    from gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
    from gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
    from gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
```

I can reproduce this exception in the test suite by commenting out the hook in the test helper: https://github.com/stulentsev/resque-multi-job-forks/blob/master/test/helper.rb#L67

**Comment by greggroth** [comment]
Fixed in #20
